name: Automated Unit Testing

on: 
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - workflow
      - main

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install all dependencies
        run: npm install

      - name: Run Tests
        run: npm run test-unit
